### ISSUE TITLE
Is beta=32 for the best run??

### ISSUE THREAD

**Issue by saloni-nferx** [UMCUtrecht-ECGxAI/ecgxai#2]
https://github.com/rutgervandeleur/ecgxai/blob/be05b53fe5f59dcea9b629f541aca3a1b981c545/examples/vae/train_factorecg_vae.py#L74

Its not very clear in the publication what's the beta being used for the optimal run, 

```The two most important hyperparameters in the β-VAE were the number of ECG factors and the β-value. For both, values of 8, 16, 32, 64, and 128 were evaluated. ```

**Comment by saloni-nferx** [comment]
@rutgervandeleur

**Comment by rutgervandeleur** [comment]
Hi Saloni! 32 was indeed the best beta in our dataset.
